# GET http://127.0.0.1:5174  
# homepage

# GET http://127.0.0.1:5174/snippets 
# all snippets

# POST http://127.0.0.1:5174/snippets 
# post snippet

# GET http://127.0.0.1:5174/snippets/777 
# get specific snippet
# DELETE http://127.0.0.1:5174/snippets/778 
# delete specific snippet

PUT http://127.0.0.1:5174/snippets/777
{
    "snippet":"xyz",
}

