# GET http://127.0.0.1:5174  
# homepage

# GET http://127.0.0.1:5174/snippets 
# all snippets

# POST http://127.0.0.1:5174/snippets
# Content-Type: application/json

# {
#     "title":"abc",
#     "content":"Filler content"
# }

# post snippet (valid format)
POST http://127.0.0.1:5174/snippets
Content-Type: application/json

{

}

# post snippet (invalid format)

# GET http://127.0.0.1:5174/snippets/63935a10739e24fda9c08b6d 
# get specific snippet

# DELETE http://127.0.0.1:5174/snippets/778 
# delete specific snippet

# PUT http://127.0.0.1:5174/snippets/777
# content-type: application/json

# {
#     "snippet":"xyz"
# }

